//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFRANIT.SHARAT {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SAFRANIT.SHARAT.TypesFORbook))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SAFRANIT.SHARAT.BooksList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SAFRANIT.SHARAT.Publish))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SAFRANIT.SHARAT.Clients))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SAFRANIT.SHARAT.BookToBorrow))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SAFRANIT.SHARAT.BorrowingExplaning))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SAFRANIT.SHARAT.Borrowing))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SAFRANIT.SHARAT.SignUp))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SAFRANIT.SHARAT.KindsOfBook))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypesFORbook", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class TypesFORbook : SAFRANIT.SHARAT.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAFRANIT.SHARAT.BooksList CodeBookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAFRANIT.SHARAT.KindsOfBook CodeKindOfBookField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAFRANIT.SHARAT.BooksList CodeBook {
            get {
                return this.CodeBookField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeBookField, value) != true)) {
                    this.CodeBookField = value;
                    this.RaisePropertyChanged("CodeBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAFRANIT.SHARAT.KindsOfBook CodeKindOfBook {
            get {
                return this.CodeKindOfBookField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeKindOfBookField, value) != true)) {
                    this.CodeKindOfBookField = value;
                    this.RaisePropertyChanged("CodeKindOfBook");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BooksList", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class BooksList : SAFRANIT.SHARAT.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeBookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAFRANIT.SHARAT.Publish CodePublishField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CopiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameBookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusBookField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodeBook {
            get {
                return this.CodeBookField;
            }
            set {
                if ((this.CodeBookField.Equals(value) != true)) {
                    this.CodeBookField = value;
                    this.RaisePropertyChanged("CodeBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAFRANIT.SHARAT.Publish CodePublish {
            get {
                return this.CodePublishField;
            }
            set {
                if ((object.ReferenceEquals(this.CodePublishField, value) != true)) {
                    this.CodePublishField = value;
                    this.RaisePropertyChanged("CodePublish");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Copies {
            get {
                return this.CopiesField;
            }
            set {
                if ((this.CopiesField.Equals(value) != true)) {
                    this.CopiesField = value;
                    this.RaisePropertyChanged("Copies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imagb {
            get {
                return this.ImagbField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagbField, value) != true)) {
                    this.ImagbField = value;
                    this.RaisePropertyChanged("Imagb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameBook {
            get {
                return this.NameBookField;
            }
            set {
                if ((object.ReferenceEquals(this.NameBookField, value) != true)) {
                    this.NameBookField = value;
                    this.RaisePropertyChanged("NameBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool StatusBook {
            get {
                return this.StatusBookField;
            }
            set {
                if ((this.StatusBookField.Equals(value) != true)) {
                    this.StatusBookField = value;
                    this.RaisePropertyChanged("StatusBook");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Publish", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Publish : SAFRANIT.SHARAT.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodePublishField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamePublishField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodePublish {
            get {
                return this.CodePublishField;
            }
            set {
                if ((this.CodePublishField.Equals(value) != true)) {
                    this.CodePublishField = value;
                    this.RaisePropertyChanged("CodePublish");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamePublish {
            get {
                return this.NamePublishField;
            }
            set {
                if ((object.ReferenceEquals(this.NamePublishField, value) != true)) {
                    this.NamePublishField = value;
                    this.RaisePropertyChanged("NamePublish");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Clients", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Clients : SAFRANIT.SHARAT.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChildrenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Children {
            get {
                return this.ChildrenField;
            }
            set {
                if ((this.ChildrenField.Equals(value) != true)) {
                    this.ChildrenField = value;
                    this.RaisePropertyChanged("Children");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fname {
            get {
                return this.FnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FnameField, value) != true)) {
                    this.FnameField = value;
                    this.RaisePropertyChanged("Fname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fone {
            get {
                return this.FoneField;
            }
            set {
                if ((object.ReferenceEquals(this.FoneField, value) != true)) {
                    this.FoneField = value;
                    this.RaisePropertyChanged("Fone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdClient {
            get {
                return this.IdClientField;
            }
            set {
                if ((object.ReferenceEquals(this.IdClientField, value) != true)) {
                    this.IdClientField = value;
                    this.RaisePropertyChanged("IdClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lname {
            get {
                return this.LnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LnameField, value) != true)) {
                    this.LnameField = value;
                    this.RaisePropertyChanged("Lname");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookToBorrow", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class BookToBorrow : SAFRANIT.SHARAT.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAFRANIT.SHARAT.BooksList CodeBookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeSidooryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusToBorrowField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAFRANIT.SHARAT.BooksList CodeBook {
            get {
                return this.CodeBookField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeBookField, value) != true)) {
                    this.CodeBookField = value;
                    this.RaisePropertyChanged("CodeBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodeSidoory {
            get {
                return this.CodeSidooryField;
            }
            set {
                if ((this.CodeSidooryField.Equals(value) != true)) {
                    this.CodeSidooryField = value;
                    this.RaisePropertyChanged("CodeSidoory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool StatusToBorrow {
            get {
                return this.StatusToBorrowField;
            }
            set {
                if ((this.StatusToBorrowField.Equals(value) != true)) {
                    this.StatusToBorrowField = value;
                    this.RaisePropertyChanged("StatusToBorrow");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BorrowingExplaning", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class BorrowingExplaning : SAFRANIT.SHARAT.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAFRANIT.SHARAT.BookToBorrow BookToBorrow1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAFRANIT.SHARAT.Borrowing CodeBorrowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReturningTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAFRANIT.SHARAT.BookToBorrow BookToBorrow1 {
            get {
                return this.BookToBorrow1Field;
            }
            set {
                if ((object.ReferenceEquals(this.BookToBorrow1Field, value) != true)) {
                    this.BookToBorrow1Field = value;
                    this.RaisePropertyChanged("BookToBorrow1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAFRANIT.SHARAT.Borrowing CodeBorrow {
            get {
                return this.CodeBorrowField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeBorrowField, value) != true)) {
                    this.CodeBorrowField = value;
                    this.RaisePropertyChanged("CodeBorrow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReturningTime {
            get {
                return this.ReturningTimeField;
            }
            set {
                if ((this.ReturningTimeField.Equals(value) != true)) {
                    this.ReturningTimeField = value;
                    this.RaisePropertyChanged("ReturningTime");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Borrowing", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Borrowing : SAFRANIT.SHARAT.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeBorrowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateBorrowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAFRANIT.SHARAT.Clients IdClientField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodeBorrow {
            get {
                return this.CodeBorrowField;
            }
            set {
                if ((this.CodeBorrowField.Equals(value) != true)) {
                    this.CodeBorrowField = value;
                    this.RaisePropertyChanged("CodeBorrow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateBorrow {
            get {
                return this.DateBorrowField;
            }
            set {
                if ((this.DateBorrowField.Equals(value) != true)) {
                    this.DateBorrowField = value;
                    this.RaisePropertyChanged("DateBorrow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAFRANIT.SHARAT.Clients IdClient {
            get {
                return this.IdClientField;
            }
            set {
                if ((object.ReferenceEquals(this.IdClientField, value) != true)) {
                    this.IdClientField = value;
                    this.RaisePropertyChanged("IdClient");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignUp", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class SignUp : SAFRANIT.SHARAT.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndSignTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SAFRANIT.SHARAT.Clients IdClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SignDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndSignTime {
            get {
                return this.EndSignTimeField;
            }
            set {
                if ((this.EndSignTimeField.Equals(value) != true)) {
                    this.EndSignTimeField = value;
                    this.RaisePropertyChanged("EndSignTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAFRANIT.SHARAT.Clients IdClient {
            get {
                return this.IdClientField;
            }
            set {
                if ((object.ReferenceEquals(this.IdClientField, value) != true)) {
                    this.IdClientField = value;
                    this.RaisePropertyChanged("IdClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SignDate {
            get {
                return this.SignDateField;
            }
            set {
                if ((this.SignDateField.Equals(value) != true)) {
                    this.SignDateField = value;
                    this.RaisePropertyChanged("SignDate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KindsOfBook", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class KindsOfBook : SAFRANIT.SHARAT.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeKindOfBookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameKindOfBookField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodeKindOfBook {
            get {
                return this.CodeKindOfBookField;
            }
            set {
                if ((this.CodeKindOfBookField.Equals(value) != true)) {
                    this.CodeKindOfBookField = value;
                    this.RaisePropertyChanged("CodeKindOfBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameKindOfBook {
            get {
                return this.NameKindOfBookField;
            }
            set {
                if ((object.ReferenceEquals(this.NameKindOfBookField, value) != true)) {
                    this.NameKindOfBookField = value;
                    this.RaisePropertyChanged("NameKindOfBook");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SHARAT.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddKindsOfBook", ReplyAction="http://tempuri.org/IService1/AddKindsOfBookResponse")]
        void AddKindsOfBook(SAFRANIT.SHARAT.KindsOfBook kindsOfBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddKindsOfBook", ReplyAction="http://tempuri.org/IService1/AddKindsOfBookResponse")]
        System.Threading.Tasks.Task AddKindsOfBookAsync(SAFRANIT.SHARAT.KindsOfBook kindsOfBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTypesFORbook", ReplyAction="http://tempuri.org/IService1/AddTypesFORbookResponse")]
        void AddTypesFORbook(SAFRANIT.SHARAT.TypesFORbook typesFORbook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTypesFORbook", ReplyAction="http://tempuri.org/IService1/AddTypesFORbookResponse")]
        System.Threading.Tasks.Task AddTypesFORbookAsync(SAFRANIT.SHARAT.TypesFORbook typesFORbook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddClients", ReplyAction="http://tempuri.org/IService1/AddClientsResponse")]
        void AddClients(SAFRANIT.SHARAT.Clients clients);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddClients", ReplyAction="http://tempuri.org/IService1/AddClientsResponse")]
        System.Threading.Tasks.Task AddClientsAsync(SAFRANIT.SHARAT.Clients clients);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPublish", ReplyAction="http://tempuri.org/IService1/AddPublishResponse")]
        void AddPublish(SAFRANIT.SHARAT.Publish publish);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPublish", ReplyAction="http://tempuri.org/IService1/AddPublishResponse")]
        System.Threading.Tasks.Task AddPublishAsync(SAFRANIT.SHARAT.Publish publish);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBooksList", ReplyAction="http://tempuri.org/IService1/AddBooksListResponse")]
        void AddBooksList(SAFRANIT.SHARAT.BooksList booksList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBooksList", ReplyAction="http://tempuri.org/IService1/AddBooksListResponse")]
        System.Threading.Tasks.Task AddBooksListAsync(SAFRANIT.SHARAT.BooksList booksList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBookToBorrow", ReplyAction="http://tempuri.org/IService1/AddBookToBorrowResponse")]
        void AddBookToBorrow(SAFRANIT.SHARAT.BookToBorrow bookToBorrow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBookToBorrow", ReplyAction="http://tempuri.org/IService1/AddBookToBorrowResponse")]
        System.Threading.Tasks.Task AddBookToBorrowAsync(SAFRANIT.SHARAT.BookToBorrow bookToBorrow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBorrowingExplaning", ReplyAction="http://tempuri.org/IService1/AddBorrowingExplaningResponse")]
        void AddBorrowingExplaning(SAFRANIT.SHARAT.BorrowingExplaning borrowingExplaning);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBorrowingExplaning", ReplyAction="http://tempuri.org/IService1/AddBorrowingExplaningResponse")]
        System.Threading.Tasks.Task AddBorrowingExplaningAsync(SAFRANIT.SHARAT.BorrowingExplaning borrowingExplaning);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddSignUp", ReplyAction="http://tempuri.org/IService1/AddSignUpResponse")]
        void AddSignUp(SAFRANIT.SHARAT.SignUp signUp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddSignUp", ReplyAction="http://tempuri.org/IService1/AddSignUpResponse")]
        System.Threading.Tasks.Task AddSignUpAsync(SAFRANIT.SHARAT.SignUp signUp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBorrowimg", ReplyAction="http://tempuri.org/IService1/AddBorrowimgResponse")]
        void AddBorrowimg(SAFRANIT.SHARAT.Borrowing borrowing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBorrowimg", ReplyAction="http://tempuri.org/IService1/AddBorrowimgResponse")]
        System.Threading.Tasks.Task AddBorrowimgAsync(SAFRANIT.SHARAT.Borrowing borrowing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateKindsOfBook", ReplyAction="http://tempuri.org/IService1/UpdateKindsOfBookResponse")]
        void UpdateKindsOfBook(SAFRANIT.SHARAT.KindsOfBook kindsOfBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateKindsOfBook", ReplyAction="http://tempuri.org/IService1/UpdateKindsOfBookResponse")]
        System.Threading.Tasks.Task UpdateKindsOfBookAsync(SAFRANIT.SHARAT.KindsOfBook kindsOfBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTypesFORbook", ReplyAction="http://tempuri.org/IService1/UpdateTypesFORbookResponse")]
        void UpdateTypesFORbook(SAFRANIT.SHARAT.TypesFORbook typesFORbook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTypesFORbook", ReplyAction="http://tempuri.org/IService1/UpdateTypesFORbookResponse")]
        System.Threading.Tasks.Task UpdateTypesFORbookAsync(SAFRANIT.SHARAT.TypesFORbook typesFORbook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateClients", ReplyAction="http://tempuri.org/IService1/UpdateClientsResponse")]
        void UpdateClients(SAFRANIT.SHARAT.Clients clients);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateClients", ReplyAction="http://tempuri.org/IService1/UpdateClientsResponse")]
        System.Threading.Tasks.Task UpdateClientsAsync(SAFRANIT.SHARAT.Clients clients);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePublish", ReplyAction="http://tempuri.org/IService1/UpdatePublishResponse")]
        void UpdatePublish(SAFRANIT.SHARAT.Publish publish);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePublish", ReplyAction="http://tempuri.org/IService1/UpdatePublishResponse")]
        System.Threading.Tasks.Task UpdatePublishAsync(SAFRANIT.SHARAT.Publish publish);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBooksList", ReplyAction="http://tempuri.org/IService1/UpdateBooksListResponse")]
        void UpdateBooksList(SAFRANIT.SHARAT.BooksList booksList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBooksList", ReplyAction="http://tempuri.org/IService1/UpdateBooksListResponse")]
        System.Threading.Tasks.Task UpdateBooksListAsync(SAFRANIT.SHARAT.BooksList booksList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBookToBorrow", ReplyAction="http://tempuri.org/IService1/UpdateBookToBorrowResponse")]
        void UpdateBookToBorrow(SAFRANIT.SHARAT.BookToBorrow bookToBorrow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBookToBorrow", ReplyAction="http://tempuri.org/IService1/UpdateBookToBorrowResponse")]
        System.Threading.Tasks.Task UpdateBookToBorrowAsync(SAFRANIT.SHARAT.BookToBorrow bookToBorrow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBorrowingExplaning", ReplyAction="http://tempuri.org/IService1/UpdateBorrowingExplaningResponse")]
        void UpdateBorrowingExplaning(SAFRANIT.SHARAT.BorrowingExplaning borrowingExplaning);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBorrowingExplaning", ReplyAction="http://tempuri.org/IService1/UpdateBorrowingExplaningResponse")]
        System.Threading.Tasks.Task UpdateBorrowingExplaningAsync(SAFRANIT.SHARAT.BorrowingExplaning borrowingExplaning);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateSignUp", ReplyAction="http://tempuri.org/IService1/UpdateSignUpResponse")]
        void UpdateSignUp(SAFRANIT.SHARAT.SignUp signUp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateSignUp", ReplyAction="http://tempuri.org/IService1/UpdateSignUpResponse")]
        System.Threading.Tasks.Task UpdateSignUpAsync(SAFRANIT.SHARAT.SignUp signUp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBorrowing", ReplyAction="http://tempuri.org/IService1/UpdateBorrowingResponse")]
        void UpdateBorrowing(SAFRANIT.SHARAT.Borrowing borrowing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBorrowing", ReplyAction="http://tempuri.org/IService1/UpdateBorrowingResponse")]
        System.Threading.Tasks.Task UpdateBorrowingAsync(SAFRANIT.SHARAT.Borrowing borrowing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStatusKindsOfBook", ReplyAction="http://tempuri.org/IService1/DeleteStatusKindsOfBookResponse")]
        void DeleteStatusKindsOfBook(SAFRANIT.SHARAT.KindsOfBook kindsOfBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStatusKindsOfBook", ReplyAction="http://tempuri.org/IService1/DeleteStatusKindsOfBookResponse")]
        System.Threading.Tasks.Task DeleteStatusKindsOfBookAsync(SAFRANIT.SHARAT.KindsOfBook kindsOfBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStatusTypesFORbook", ReplyAction="http://tempuri.org/IService1/DeleteStatusTypesFORbookResponse")]
        void DeleteStatusTypesFORbook(SAFRANIT.SHARAT.TypesFORbook typesFORbook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStatusTypesFORbook", ReplyAction="http://tempuri.org/IService1/DeleteStatusTypesFORbookResponse")]
        System.Threading.Tasks.Task DeleteStatusTypesFORbookAsync(SAFRANIT.SHARAT.TypesFORbook typesFORbook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStatusClients", ReplyAction="http://tempuri.org/IService1/DeleteStatusClientsResponse")]
        void DeleteStatusClients(SAFRANIT.SHARAT.Clients clients);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStatusClients", ReplyAction="http://tempuri.org/IService1/DeleteStatusClientsResponse")]
        System.Threading.Tasks.Task DeleteStatusClientsAsync(SAFRANIT.SHARAT.Clients clients);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStatusPublish", ReplyAction="http://tempuri.org/IService1/DeleteStatusPublishResponse")]
        void DeleteStatusPublish(SAFRANIT.SHARAT.Publish publish);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStatusPublish", ReplyAction="http://tempuri.org/IService1/DeleteStatusPublishResponse")]
        System.Threading.Tasks.Task DeleteStatusPublishAsync(SAFRANIT.SHARAT.Publish publish);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStatusBooksList", ReplyAction="http://tempuri.org/IService1/DeleteStatusBooksListResponse")]
        void DeleteStatusBooksList(SAFRANIT.SHARAT.BooksList booksList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStatusBooksList", ReplyAction="http://tempuri.org/IService1/DeleteStatusBooksListResponse")]
        System.Threading.Tasks.Task DeleteStatusBooksListAsync(SAFRANIT.SHARAT.BooksList booksList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStatusBookToBorrow", ReplyAction="http://tempuri.org/IService1/DeleteStatusBookToBorrowResponse")]
        void DeleteStatusBookToBorrow(SAFRANIT.SHARAT.BookToBorrow bookToBorrow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStatusBookToBorrow", ReplyAction="http://tempuri.org/IService1/DeleteStatusBookToBorrowResponse")]
        System.Threading.Tasks.Task DeleteStatusBookToBorrowAsync(SAFRANIT.SHARAT.BookToBorrow bookToBorrow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStatusBorrowingExplaning", ReplyAction="http://tempuri.org/IService1/DeleteStatusBorrowingExplaningResponse")]
        void DeleteStatusBorrowingExplaning(SAFRANIT.SHARAT.BorrowingExplaning borrowingExplaning);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStatusBorrowingExplaning", ReplyAction="http://tempuri.org/IService1/DeleteStatusBorrowingExplaningResponse")]
        System.Threading.Tasks.Task DeleteStatusBorrowingExplaningAsync(SAFRANIT.SHARAT.BorrowingExplaning borrowingExplaning);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStatusSignUp", ReplyAction="http://tempuri.org/IService1/DeleteStatusSignUpResponse")]
        void DeleteStatusSignUp(SAFRANIT.SHARAT.SignUp signUp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStatusSignUp", ReplyAction="http://tempuri.org/IService1/DeleteStatusSignUpResponse")]
        System.Threading.Tasks.Task DeleteStatusSignUpAsync(SAFRANIT.SHARAT.SignUp signUp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStatusBorrowing", ReplyAction="http://tempuri.org/IService1/DeleteStatusBorrowingResponse")]
        void DeleteStatusBorrowing(SAFRANIT.SHARAT.Borrowing borrowing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStatusBorrowing", ReplyAction="http://tempuri.org/IService1/DeleteStatusBorrowingResponse")]
        System.Threading.Tasks.Task DeleteStatusBorrowingAsync(SAFRANIT.SHARAT.Borrowing borrowing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetKindsOfBookBySelect", ReplyAction="http://tempuri.org/IService1/GetKindsOfBookBySelectResponse")]
        SAFRANIT.SHARAT.KindsOfBook[] GetKindsOfBookBySelect(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetKindsOfBookBySelect", ReplyAction="http://tempuri.org/IService1/GetKindsOfBookBySelectResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.KindsOfBook[]> GetKindsOfBookBySelectAsync(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTypesFORbookBySelect", ReplyAction="http://tempuri.org/IService1/GetTypesFORbookBySelectResponse")]
        SAFRANIT.SHARAT.TypesFORbook[] GetTypesFORbookBySelect(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTypesFORbookBySelect", ReplyAction="http://tempuri.org/IService1/GetTypesFORbookBySelectResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.TypesFORbook[]> GetTypesFORbookBySelectAsync(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClientsBySelect", ReplyAction="http://tempuri.org/IService1/GetClientsBySelectResponse")]
        SAFRANIT.SHARAT.Clients[] GetClientsBySelect(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClientsBySelect", ReplyAction="http://tempuri.org/IService1/GetClientsBySelectResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.Clients[]> GetClientsBySelectAsync(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPublishBySelect", ReplyAction="http://tempuri.org/IService1/GetPublishBySelectResponse")]
        SAFRANIT.SHARAT.Publish[] GetPublishBySelect(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPublishBySelect", ReplyAction="http://tempuri.org/IService1/GetPublishBySelectResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.Publish[]> GetPublishBySelectAsync(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBooksListBySelect", ReplyAction="http://tempuri.org/IService1/GetBooksListBySelectResponse")]
        SAFRANIT.SHARAT.BooksList[] GetBooksListBySelect(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBooksListBySelect", ReplyAction="http://tempuri.org/IService1/GetBooksListBySelectResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.BooksList[]> GetBooksListBySelectAsync(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookToBorrowBySelect", ReplyAction="http://tempuri.org/IService1/GetBookToBorrowBySelectResponse")]
        SAFRANIT.SHARAT.BookToBorrow[] GetBookToBorrowBySelect(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookToBorrowBySelect", ReplyAction="http://tempuri.org/IService1/GetBookToBorrowBySelectResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.BookToBorrow[]> GetBookToBorrowBySelectAsync(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBorrowingExplaningBySelect", ReplyAction="http://tempuri.org/IService1/GetBorrowingExplaningBySelectResponse")]
        SAFRANIT.SHARAT.BorrowingExplaning[] GetBorrowingExplaningBySelect(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBorrowingExplaningBySelect", ReplyAction="http://tempuri.org/IService1/GetBorrowingExplaningBySelectResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.BorrowingExplaning[]> GetBorrowingExplaningBySelectAsync(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSignUpBySelect", ReplyAction="http://tempuri.org/IService1/GetSignUpBySelectResponse")]
        SAFRANIT.SHARAT.SignUp[] GetSignUpBySelect(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSignUpBySelect", ReplyAction="http://tempuri.org/IService1/GetSignUpBySelectResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.SignUp[]> GetSignUpBySelectAsync(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBorrowingBySelect", ReplyAction="http://tempuri.org/IService1/GetBorrowingBySelectResponse")]
        SAFRANIT.SHARAT.Borrowing[] GetBorrowingBySelect(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBorrowingBySelect", ReplyAction="http://tempuri.org/IService1/GetBorrowingBySelectResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.Borrowing[]> GetBorrowingBySelectAsync(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetKindsOfBookByCode", ReplyAction="http://tempuri.org/IService1/GetKindsOfBookByCodeResponse")]
        SAFRANIT.SHARAT.KindsOfBook GetKindsOfBookByCode(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetKindsOfBookByCode", ReplyAction="http://tempuri.org/IService1/GetKindsOfBookByCodeResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.KindsOfBook> GetKindsOfBookByCodeAsync(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTypesFORbookByCode", ReplyAction="http://tempuri.org/IService1/GetTypesFORbookByCodeResponse")]
        SAFRANIT.SHARAT.TypesFORbook GetTypesFORbookByCode(int code, int cd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTypesFORbookByCode", ReplyAction="http://tempuri.org/IService1/GetTypesFORbookByCodeResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.TypesFORbook> GetTypesFORbookByCodeAsync(int code, int cd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClientsByCode", ReplyAction="http://tempuri.org/IService1/GetClientsByCodeResponse")]
        SAFRANIT.SHARAT.Clients GetClientsByCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClientsByCode", ReplyAction="http://tempuri.org/IService1/GetClientsByCodeResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.Clients> GetClientsByCodeAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPublishByCode", ReplyAction="http://tempuri.org/IService1/GetPublishByCodeResponse")]
        SAFRANIT.SHARAT.Publish GetPublishByCode(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPublishByCode", ReplyAction="http://tempuri.org/IService1/GetPublishByCodeResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.Publish> GetPublishByCodeAsync(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBooksListByCode", ReplyAction="http://tempuri.org/IService1/GetBooksListByCodeResponse")]
        SAFRANIT.SHARAT.BooksList GetBooksListByCode(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBooksListByCode", ReplyAction="http://tempuri.org/IService1/GetBooksListByCodeResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.BooksList> GetBooksListByCodeAsync(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookToBorrowByCode", ReplyAction="http://tempuri.org/IService1/GetBookToBorrowByCodeResponse")]
        SAFRANIT.SHARAT.BookToBorrow GetBookToBorrowByCode(int code, int cd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookToBorrowByCode", ReplyAction="http://tempuri.org/IService1/GetBookToBorrowByCodeResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.BookToBorrow> GetBookToBorrowByCodeAsync(int code, int cd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBorrowingExplaningByCode", ReplyAction="http://tempuri.org/IService1/GetBorrowingExplaningByCodeResponse")]
        SAFRANIT.SHARAT.BorrowingExplaning GetBorrowingExplaningByCode(int code, int cd, int cdd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBorrowingExplaningByCode", ReplyAction="http://tempuri.org/IService1/GetBorrowingExplaningByCodeResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.BorrowingExplaning> GetBorrowingExplaningByCodeAsync(int code, int cd, int cdd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSignUpByCode", ReplyAction="http://tempuri.org/IService1/GetSignUpByCodeResponse")]
        SAFRANIT.SHARAT.SignUp GetSignUpByCode(string code, System.DateTime cd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSignUpByCode", ReplyAction="http://tempuri.org/IService1/GetSignUpByCodeResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.SignUp> GetSignUpByCodeAsync(string code, System.DateTime cd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBorrowingByCode", ReplyAction="http://tempuri.org/IService1/GetBorrowingByCodeResponse")]
        SAFRANIT.SHARAT.Borrowing GetBorrowingByCode(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBorrowingByCode", ReplyAction="http://tempuri.org/IService1/GetBorrowingByCodeResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.Borrowing> GetBorrowingByCodeAsync(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListKindsOfBookBySelectedContain", ReplyAction="http://tempuri.org/IService1/GetListKindsOfBookBySelectedContainResponse")]
        SAFRANIT.SHARAT.KindsOfBook[] GetListKindsOfBookBySelectedContain(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListKindsOfBookBySelectedContain", ReplyAction="http://tempuri.org/IService1/GetListKindsOfBookBySelectedContainResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.KindsOfBook[]> GetListKindsOfBookBySelectedContainAsync(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListTypesFORbookBySelectedContain", ReplyAction="http://tempuri.org/IService1/GetListTypesFORbookBySelectedContainResponse")]
        SAFRANIT.SHARAT.TypesFORbook[] GetListTypesFORbookBySelectedContain(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListTypesFORbookBySelectedContain", ReplyAction="http://tempuri.org/IService1/GetListTypesFORbookBySelectedContainResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.TypesFORbook[]> GetListTypesFORbookBySelectedContainAsync(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListClientsBySelectedContain", ReplyAction="http://tempuri.org/IService1/GetListClientsBySelectedContainResponse")]
        SAFRANIT.SHARAT.Clients[] GetListClientsBySelectedContain(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListClientsBySelectedContain", ReplyAction="http://tempuri.org/IService1/GetListClientsBySelectedContainResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.Clients[]> GetListClientsBySelectedContainAsync(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListPublishBySelectedContain", ReplyAction="http://tempuri.org/IService1/GetListPublishBySelectedContainResponse")]
        SAFRANIT.SHARAT.Publish[] GetListPublishBySelectedContain(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListPublishBySelectedContain", ReplyAction="http://tempuri.org/IService1/GetListPublishBySelectedContainResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.Publish[]> GetListPublishBySelectedContainAsync(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListBooksListBySelectedContain", ReplyAction="http://tempuri.org/IService1/GetListBooksListBySelectedContainResponse")]
        SAFRANIT.SHARAT.BooksList[] GetListBooksListBySelectedContain(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListBooksListBySelectedContain", ReplyAction="http://tempuri.org/IService1/GetListBooksListBySelectedContainResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.BooksList[]> GetListBooksListBySelectedContainAsync(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListBookToBorrowBySelectedContain", ReplyAction="http://tempuri.org/IService1/GetListBookToBorrowBySelectedContainResponse")]
        SAFRANIT.SHARAT.BookToBorrow[] GetListBookToBorrowBySelectedContain(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListBookToBorrowBySelectedContain", ReplyAction="http://tempuri.org/IService1/GetListBookToBorrowBySelectedContainResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.BookToBorrow[]> GetListBookToBorrowBySelectedContainAsync(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListBorrowingExplaningBySelectedContain", ReplyAction="http://tempuri.org/IService1/GetListBorrowingExplaningBySelectedContainResponse")]
        SAFRANIT.SHARAT.BorrowingExplaning[] GetListBorrowingExplaningBySelectedContain(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListBorrowingExplaningBySelectedContain", ReplyAction="http://tempuri.org/IService1/GetListBorrowingExplaningBySelectedContainResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.BorrowingExplaning[]> GetListBorrowingExplaningBySelectedContainAsync(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListSignUpBySelectedContain", ReplyAction="http://tempuri.org/IService1/GetListSignUpBySelectedContainResponse")]
        SAFRANIT.SHARAT.SignUp[] GetListSignUpBySelectedContain(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListSignUpBySelectedContain", ReplyAction="http://tempuri.org/IService1/GetListSignUpBySelectedContainResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.SignUp[]> GetListSignUpBySelectedContainAsync(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListBorrowingBySelectedContain", ReplyAction="http://tempuri.org/IService1/GetListBorrowingBySelectedContainResponse")]
        SAFRANIT.SHARAT.Borrowing[] GetListBorrowingBySelectedContain(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListBorrowingBySelectedContain", ReplyAction="http://tempuri.org/IService1/GetListBorrowingBySelectedContainResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.Borrowing[]> GetListBorrowingBySelectedContainAsync(string nameField, string st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListKindsOfBook", ReplyAction="http://tempuri.org/IService1/GetListKindsOfBookResponse")]
        SAFRANIT.SHARAT.KindsOfBook[] GetListKindsOfBook();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListKindsOfBook", ReplyAction="http://tempuri.org/IService1/GetListKindsOfBookResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.KindsOfBook[]> GetListKindsOfBookAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListTypesFORbook", ReplyAction="http://tempuri.org/IService1/GetListTypesFORbookResponse")]
        SAFRANIT.SHARAT.TypesFORbook[] GetListTypesFORbook();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListTypesFORbook", ReplyAction="http://tempuri.org/IService1/GetListTypesFORbookResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.TypesFORbook[]> GetListTypesFORbookAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListClients", ReplyAction="http://tempuri.org/IService1/GetListClientsResponse")]
        SAFRANIT.SHARAT.Clients[] GetListClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListClients", ReplyAction="http://tempuri.org/IService1/GetListClientsResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.Clients[]> GetListClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListPublish", ReplyAction="http://tempuri.org/IService1/GetListPublishResponse")]
        SAFRANIT.SHARAT.Publish[] GetListPublish();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListPublish", ReplyAction="http://tempuri.org/IService1/GetListPublishResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.Publish[]> GetListPublishAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListBooksList", ReplyAction="http://tempuri.org/IService1/GetListBooksListResponse")]
        SAFRANIT.SHARAT.BooksList[] GetListBooksList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListBooksList", ReplyAction="http://tempuri.org/IService1/GetListBooksListResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.BooksList[]> GetListBooksListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListBookToBorrow", ReplyAction="http://tempuri.org/IService1/GetListBookToBorrowResponse")]
        SAFRANIT.SHARAT.BookToBorrow[] GetListBookToBorrow();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListBookToBorrow", ReplyAction="http://tempuri.org/IService1/GetListBookToBorrowResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.BookToBorrow[]> GetListBookToBorrowAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListBorrowingExplaning", ReplyAction="http://tempuri.org/IService1/GetListBorrowingExplaningResponse")]
        SAFRANIT.SHARAT.BorrowingExplaning[] GetListBorrowingExplaning();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListBorrowingExplaning", ReplyAction="http://tempuri.org/IService1/GetListBorrowingExplaningResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.BorrowingExplaning[]> GetListBorrowingExplaningAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListSignUp", ReplyAction="http://tempuri.org/IService1/GetListSignUpResponse")]
        SAFRANIT.SHARAT.SignUp[] GetListSignUp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListSignUp", ReplyAction="http://tempuri.org/IService1/GetListSignUpResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.SignUp[]> GetListSignUpAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListBorrowing", ReplyAction="http://tempuri.org/IService1/GetListBorrowingResponse")]
        SAFRANIT.SHARAT.Borrowing[] GetListBorrowing();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListBorrowing", ReplyAction="http://tempuri.org/IService1/GetListBorrowingResponse")]
        System.Threading.Tasks.Task<SAFRANIT.SHARAT.Borrowing[]> GetListBorrowingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNextKeyKindsOfBook", ReplyAction="http://tempuri.org/IService1/GetNextKeyKindsOfBookResponse")]
        int GetNextKeyKindsOfBook();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNextKeyKindsOfBook", ReplyAction="http://tempuri.org/IService1/GetNextKeyKindsOfBookResponse")]
        System.Threading.Tasks.Task<int> GetNextKeyKindsOfBookAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNextKeyPublish", ReplyAction="http://tempuri.org/IService1/GetNextKeyPublishResponse")]
        int GetNextKeyPublish();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNextKeyPublish", ReplyAction="http://tempuri.org/IService1/GetNextKeyPublishResponse")]
        System.Threading.Tasks.Task<int> GetNextKeyPublishAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNextKeyBooksList", ReplyAction="http://tempuri.org/IService1/GetNextKeyBooksListResponse")]
        int GetNextKeyBooksList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNextKeyBooksList", ReplyAction="http://tempuri.org/IService1/GetNextKeyBooksListResponse")]
        System.Threading.Tasks.Task<int> GetNextKeyBooksListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNextKeyBorrowing", ReplyAction="http://tempuri.org/IService1/GetNextKeyBorrowingResponse")]
        int GetNextKeyBorrowing();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNextKeyBorrowing", ReplyAction="http://tempuri.org/IService1/GetNextKeyBorrowingResponse")]
        System.Threading.Tasks.Task<int> GetNextKeyBorrowingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNextKeyBookToBorrow", ReplyAction="http://tempuri.org/IService1/GetNextKeyBookToBorrowResponse")]
        int GetNextKeyBookToBorrow();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNextKeyBookToBorrow", ReplyAction="http://tempuri.org/IService1/GetNextKeyBookToBorrowResponse")]
        System.Threading.Tasks.Task<int> GetNextKeyBookToBorrowAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCurrentPath", ReplyAction="http://tempuri.org/IService1/GetCurrentPathResponse")]
        string GetCurrentPath();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCurrentPath", ReplyAction="http://tempuri.org/IService1/GetCurrentPathResponse")]
        System.Threading.Tasks.Task<string> GetCurrentPathAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveImg", ReplyAction="http://tempuri.org/IService1/SaveImgResponse")]
        void SaveImg(byte[] imageArr, string nameFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveImg", ReplyAction="http://tempuri.org/IService1/SaveImgResponse")]
        System.Threading.Tasks.Task SaveImgAsync(byte[] imageArr, string nameFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImage", ReplyAction="http://tempuri.org/IService1/GetImageResponse")]
        byte[] GetImage(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImage", ReplyAction="http://tempuri.org/IService1/GetImageResponse")]
        System.Threading.Tasks.Task<byte[]> GetImageAsync(string fileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SAFRANIT.SHARAT.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SAFRANIT.SHARAT.IService1>, SAFRANIT.SHARAT.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddKindsOfBook(SAFRANIT.SHARAT.KindsOfBook kindsOfBook) {
            base.Channel.AddKindsOfBook(kindsOfBook);
        }
        
        public System.Threading.Tasks.Task AddKindsOfBookAsync(SAFRANIT.SHARAT.KindsOfBook kindsOfBook) {
            return base.Channel.AddKindsOfBookAsync(kindsOfBook);
        }
        
        public void AddTypesFORbook(SAFRANIT.SHARAT.TypesFORbook typesFORbook) {
            base.Channel.AddTypesFORbook(typesFORbook);
        }
        
        public System.Threading.Tasks.Task AddTypesFORbookAsync(SAFRANIT.SHARAT.TypesFORbook typesFORbook) {
            return base.Channel.AddTypesFORbookAsync(typesFORbook);
        }
        
        public void AddClients(SAFRANIT.SHARAT.Clients clients) {
            base.Channel.AddClients(clients);
        }
        
        public System.Threading.Tasks.Task AddClientsAsync(SAFRANIT.SHARAT.Clients clients) {
            return base.Channel.AddClientsAsync(clients);
        }
        
        public void AddPublish(SAFRANIT.SHARAT.Publish publish) {
            base.Channel.AddPublish(publish);
        }
        
        public System.Threading.Tasks.Task AddPublishAsync(SAFRANIT.SHARAT.Publish publish) {
            return base.Channel.AddPublishAsync(publish);
        }
        
        public void AddBooksList(SAFRANIT.SHARAT.BooksList booksList) {
            base.Channel.AddBooksList(booksList);
        }
        
        public System.Threading.Tasks.Task AddBooksListAsync(SAFRANIT.SHARAT.BooksList booksList) {
            return base.Channel.AddBooksListAsync(booksList);
        }
        
        public void AddBookToBorrow(SAFRANIT.SHARAT.BookToBorrow bookToBorrow) {
            base.Channel.AddBookToBorrow(bookToBorrow);
        }
        
        public System.Threading.Tasks.Task AddBookToBorrowAsync(SAFRANIT.SHARAT.BookToBorrow bookToBorrow) {
            return base.Channel.AddBookToBorrowAsync(bookToBorrow);
        }
        
        public void AddBorrowingExplaning(SAFRANIT.SHARAT.BorrowingExplaning borrowingExplaning) {
            base.Channel.AddBorrowingExplaning(borrowingExplaning);
        }
        
        public System.Threading.Tasks.Task AddBorrowingExplaningAsync(SAFRANIT.SHARAT.BorrowingExplaning borrowingExplaning) {
            return base.Channel.AddBorrowingExplaningAsync(borrowingExplaning);
        }
        
        public void AddSignUp(SAFRANIT.SHARAT.SignUp signUp) {
            base.Channel.AddSignUp(signUp);
        }
        
        public System.Threading.Tasks.Task AddSignUpAsync(SAFRANIT.SHARAT.SignUp signUp) {
            return base.Channel.AddSignUpAsync(signUp);
        }
        
        public void AddBorrowimg(SAFRANIT.SHARAT.Borrowing borrowing) {
            base.Channel.AddBorrowimg(borrowing);
        }
        
        public System.Threading.Tasks.Task AddBorrowimgAsync(SAFRANIT.SHARAT.Borrowing borrowing) {
            return base.Channel.AddBorrowimgAsync(borrowing);
        }
        
        public void UpdateKindsOfBook(SAFRANIT.SHARAT.KindsOfBook kindsOfBook) {
            base.Channel.UpdateKindsOfBook(kindsOfBook);
        }
        
        public System.Threading.Tasks.Task UpdateKindsOfBookAsync(SAFRANIT.SHARAT.KindsOfBook kindsOfBook) {
            return base.Channel.UpdateKindsOfBookAsync(kindsOfBook);
        }
        
        public void UpdateTypesFORbook(SAFRANIT.SHARAT.TypesFORbook typesFORbook) {
            base.Channel.UpdateTypesFORbook(typesFORbook);
        }
        
        public System.Threading.Tasks.Task UpdateTypesFORbookAsync(SAFRANIT.SHARAT.TypesFORbook typesFORbook) {
            return base.Channel.UpdateTypesFORbookAsync(typesFORbook);
        }
        
        public void UpdateClients(SAFRANIT.SHARAT.Clients clients) {
            base.Channel.UpdateClients(clients);
        }
        
        public System.Threading.Tasks.Task UpdateClientsAsync(SAFRANIT.SHARAT.Clients clients) {
            return base.Channel.UpdateClientsAsync(clients);
        }
        
        public void UpdatePublish(SAFRANIT.SHARAT.Publish publish) {
            base.Channel.UpdatePublish(publish);
        }
        
        public System.Threading.Tasks.Task UpdatePublishAsync(SAFRANIT.SHARAT.Publish publish) {
            return base.Channel.UpdatePublishAsync(publish);
        }
        
        public void UpdateBooksList(SAFRANIT.SHARAT.BooksList booksList) {
            base.Channel.UpdateBooksList(booksList);
        }
        
        public System.Threading.Tasks.Task UpdateBooksListAsync(SAFRANIT.SHARAT.BooksList booksList) {
            return base.Channel.UpdateBooksListAsync(booksList);
        }
        
        public void UpdateBookToBorrow(SAFRANIT.SHARAT.BookToBorrow bookToBorrow) {
            base.Channel.UpdateBookToBorrow(bookToBorrow);
        }
        
        public System.Threading.Tasks.Task UpdateBookToBorrowAsync(SAFRANIT.SHARAT.BookToBorrow bookToBorrow) {
            return base.Channel.UpdateBookToBorrowAsync(bookToBorrow);
        }
        
        public void UpdateBorrowingExplaning(SAFRANIT.SHARAT.BorrowingExplaning borrowingExplaning) {
            base.Channel.UpdateBorrowingExplaning(borrowingExplaning);
        }
        
        public System.Threading.Tasks.Task UpdateBorrowingExplaningAsync(SAFRANIT.SHARAT.BorrowingExplaning borrowingExplaning) {
            return base.Channel.UpdateBorrowingExplaningAsync(borrowingExplaning);
        }
        
        public void UpdateSignUp(SAFRANIT.SHARAT.SignUp signUp) {
            base.Channel.UpdateSignUp(signUp);
        }
        
        public System.Threading.Tasks.Task UpdateSignUpAsync(SAFRANIT.SHARAT.SignUp signUp) {
            return base.Channel.UpdateSignUpAsync(signUp);
        }
        
        public void UpdateBorrowing(SAFRANIT.SHARAT.Borrowing borrowing) {
            base.Channel.UpdateBorrowing(borrowing);
        }
        
        public System.Threading.Tasks.Task UpdateBorrowingAsync(SAFRANIT.SHARAT.Borrowing borrowing) {
            return base.Channel.UpdateBorrowingAsync(borrowing);
        }
        
        public void DeleteStatusKindsOfBook(SAFRANIT.SHARAT.KindsOfBook kindsOfBook) {
            base.Channel.DeleteStatusKindsOfBook(kindsOfBook);
        }
        
        public System.Threading.Tasks.Task DeleteStatusKindsOfBookAsync(SAFRANIT.SHARAT.KindsOfBook kindsOfBook) {
            return base.Channel.DeleteStatusKindsOfBookAsync(kindsOfBook);
        }
        
        public void DeleteStatusTypesFORbook(SAFRANIT.SHARAT.TypesFORbook typesFORbook) {
            base.Channel.DeleteStatusTypesFORbook(typesFORbook);
        }
        
        public System.Threading.Tasks.Task DeleteStatusTypesFORbookAsync(SAFRANIT.SHARAT.TypesFORbook typesFORbook) {
            return base.Channel.DeleteStatusTypesFORbookAsync(typesFORbook);
        }
        
        public void DeleteStatusClients(SAFRANIT.SHARAT.Clients clients) {
            base.Channel.DeleteStatusClients(clients);
        }
        
        public System.Threading.Tasks.Task DeleteStatusClientsAsync(SAFRANIT.SHARAT.Clients clients) {
            return base.Channel.DeleteStatusClientsAsync(clients);
        }
        
        public void DeleteStatusPublish(SAFRANIT.SHARAT.Publish publish) {
            base.Channel.DeleteStatusPublish(publish);
        }
        
        public System.Threading.Tasks.Task DeleteStatusPublishAsync(SAFRANIT.SHARAT.Publish publish) {
            return base.Channel.DeleteStatusPublishAsync(publish);
        }
        
        public void DeleteStatusBooksList(SAFRANIT.SHARAT.BooksList booksList) {
            base.Channel.DeleteStatusBooksList(booksList);
        }
        
        public System.Threading.Tasks.Task DeleteStatusBooksListAsync(SAFRANIT.SHARAT.BooksList booksList) {
            return base.Channel.DeleteStatusBooksListAsync(booksList);
        }
        
        public void DeleteStatusBookToBorrow(SAFRANIT.SHARAT.BookToBorrow bookToBorrow) {
            base.Channel.DeleteStatusBookToBorrow(bookToBorrow);
        }
        
        public System.Threading.Tasks.Task DeleteStatusBookToBorrowAsync(SAFRANIT.SHARAT.BookToBorrow bookToBorrow) {
            return base.Channel.DeleteStatusBookToBorrowAsync(bookToBorrow);
        }
        
        public void DeleteStatusBorrowingExplaning(SAFRANIT.SHARAT.BorrowingExplaning borrowingExplaning) {
            base.Channel.DeleteStatusBorrowingExplaning(borrowingExplaning);
        }
        
        public System.Threading.Tasks.Task DeleteStatusBorrowingExplaningAsync(SAFRANIT.SHARAT.BorrowingExplaning borrowingExplaning) {
            return base.Channel.DeleteStatusBorrowingExplaningAsync(borrowingExplaning);
        }
        
        public void DeleteStatusSignUp(SAFRANIT.SHARAT.SignUp signUp) {
            base.Channel.DeleteStatusSignUp(signUp);
        }
        
        public System.Threading.Tasks.Task DeleteStatusSignUpAsync(SAFRANIT.SHARAT.SignUp signUp) {
            return base.Channel.DeleteStatusSignUpAsync(signUp);
        }
        
        public void DeleteStatusBorrowing(SAFRANIT.SHARAT.Borrowing borrowing) {
            base.Channel.DeleteStatusBorrowing(borrowing);
        }
        
        public System.Threading.Tasks.Task DeleteStatusBorrowingAsync(SAFRANIT.SHARAT.Borrowing borrowing) {
            return base.Channel.DeleteStatusBorrowingAsync(borrowing);
        }
        
        public SAFRANIT.SHARAT.KindsOfBook[] GetKindsOfBookBySelect(string nameField, string st) {
            return base.Channel.GetKindsOfBookBySelect(nameField, st);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.KindsOfBook[]> GetKindsOfBookBySelectAsync(string nameField, string st) {
            return base.Channel.GetKindsOfBookBySelectAsync(nameField, st);
        }
        
        public SAFRANIT.SHARAT.TypesFORbook[] GetTypesFORbookBySelect(string nameField, string st) {
            return base.Channel.GetTypesFORbookBySelect(nameField, st);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.TypesFORbook[]> GetTypesFORbookBySelectAsync(string nameField, string st) {
            return base.Channel.GetTypesFORbookBySelectAsync(nameField, st);
        }
        
        public SAFRANIT.SHARAT.Clients[] GetClientsBySelect(string nameField, string st) {
            return base.Channel.GetClientsBySelect(nameField, st);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.Clients[]> GetClientsBySelectAsync(string nameField, string st) {
            return base.Channel.GetClientsBySelectAsync(nameField, st);
        }
        
        public SAFRANIT.SHARAT.Publish[] GetPublishBySelect(string nameField, string st) {
            return base.Channel.GetPublishBySelect(nameField, st);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.Publish[]> GetPublishBySelectAsync(string nameField, string st) {
            return base.Channel.GetPublishBySelectAsync(nameField, st);
        }
        
        public SAFRANIT.SHARAT.BooksList[] GetBooksListBySelect(string nameField, string st) {
            return base.Channel.GetBooksListBySelect(nameField, st);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.BooksList[]> GetBooksListBySelectAsync(string nameField, string st) {
            return base.Channel.GetBooksListBySelectAsync(nameField, st);
        }
        
        public SAFRANIT.SHARAT.BookToBorrow[] GetBookToBorrowBySelect(string nameField, string st) {
            return base.Channel.GetBookToBorrowBySelect(nameField, st);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.BookToBorrow[]> GetBookToBorrowBySelectAsync(string nameField, string st) {
            return base.Channel.GetBookToBorrowBySelectAsync(nameField, st);
        }
        
        public SAFRANIT.SHARAT.BorrowingExplaning[] GetBorrowingExplaningBySelect(string nameField, string st) {
            return base.Channel.GetBorrowingExplaningBySelect(nameField, st);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.BorrowingExplaning[]> GetBorrowingExplaningBySelectAsync(string nameField, string st) {
            return base.Channel.GetBorrowingExplaningBySelectAsync(nameField, st);
        }
        
        public SAFRANIT.SHARAT.SignUp[] GetSignUpBySelect(string nameField, string st) {
            return base.Channel.GetSignUpBySelect(nameField, st);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.SignUp[]> GetSignUpBySelectAsync(string nameField, string st) {
            return base.Channel.GetSignUpBySelectAsync(nameField, st);
        }
        
        public SAFRANIT.SHARAT.Borrowing[] GetBorrowingBySelect(string nameField, string st) {
            return base.Channel.GetBorrowingBySelect(nameField, st);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.Borrowing[]> GetBorrowingBySelectAsync(string nameField, string st) {
            return base.Channel.GetBorrowingBySelectAsync(nameField, st);
        }
        
        public SAFRANIT.SHARAT.KindsOfBook GetKindsOfBookByCode(int code) {
            return base.Channel.GetKindsOfBookByCode(code);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.KindsOfBook> GetKindsOfBookByCodeAsync(int code) {
            return base.Channel.GetKindsOfBookByCodeAsync(code);
        }
        
        public SAFRANIT.SHARAT.TypesFORbook GetTypesFORbookByCode(int code, int cd) {
            return base.Channel.GetTypesFORbookByCode(code, cd);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.TypesFORbook> GetTypesFORbookByCodeAsync(int code, int cd) {
            return base.Channel.GetTypesFORbookByCodeAsync(code, cd);
        }
        
        public SAFRANIT.SHARAT.Clients GetClientsByCode(string code) {
            return base.Channel.GetClientsByCode(code);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.Clients> GetClientsByCodeAsync(string code) {
            return base.Channel.GetClientsByCodeAsync(code);
        }
        
        public SAFRANIT.SHARAT.Publish GetPublishByCode(int code) {
            return base.Channel.GetPublishByCode(code);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.Publish> GetPublishByCodeAsync(int code) {
            return base.Channel.GetPublishByCodeAsync(code);
        }
        
        public SAFRANIT.SHARAT.BooksList GetBooksListByCode(int code) {
            return base.Channel.GetBooksListByCode(code);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.BooksList> GetBooksListByCodeAsync(int code) {
            return base.Channel.GetBooksListByCodeAsync(code);
        }
        
        public SAFRANIT.SHARAT.BookToBorrow GetBookToBorrowByCode(int code, int cd) {
            return base.Channel.GetBookToBorrowByCode(code, cd);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.BookToBorrow> GetBookToBorrowByCodeAsync(int code, int cd) {
            return base.Channel.GetBookToBorrowByCodeAsync(code, cd);
        }
        
        public SAFRANIT.SHARAT.BorrowingExplaning GetBorrowingExplaningByCode(int code, int cd, int cdd) {
            return base.Channel.GetBorrowingExplaningByCode(code, cd, cdd);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.BorrowingExplaning> GetBorrowingExplaningByCodeAsync(int code, int cd, int cdd) {
            return base.Channel.GetBorrowingExplaningByCodeAsync(code, cd, cdd);
        }
        
        public SAFRANIT.SHARAT.SignUp GetSignUpByCode(string code, System.DateTime cd) {
            return base.Channel.GetSignUpByCode(code, cd);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.SignUp> GetSignUpByCodeAsync(string code, System.DateTime cd) {
            return base.Channel.GetSignUpByCodeAsync(code, cd);
        }
        
        public SAFRANIT.SHARAT.Borrowing GetBorrowingByCode(int code) {
            return base.Channel.GetBorrowingByCode(code);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.Borrowing> GetBorrowingByCodeAsync(int code) {
            return base.Channel.GetBorrowingByCodeAsync(code);
        }
        
        public SAFRANIT.SHARAT.KindsOfBook[] GetListKindsOfBookBySelectedContain(string nameField, string st) {
            return base.Channel.GetListKindsOfBookBySelectedContain(nameField, st);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.KindsOfBook[]> GetListKindsOfBookBySelectedContainAsync(string nameField, string st) {
            return base.Channel.GetListKindsOfBookBySelectedContainAsync(nameField, st);
        }
        
        public SAFRANIT.SHARAT.TypesFORbook[] GetListTypesFORbookBySelectedContain(string nameField, string st) {
            return base.Channel.GetListTypesFORbookBySelectedContain(nameField, st);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.TypesFORbook[]> GetListTypesFORbookBySelectedContainAsync(string nameField, string st) {
            return base.Channel.GetListTypesFORbookBySelectedContainAsync(nameField, st);
        }
        
        public SAFRANIT.SHARAT.Clients[] GetListClientsBySelectedContain(string nameField, string st) {
            return base.Channel.GetListClientsBySelectedContain(nameField, st);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.Clients[]> GetListClientsBySelectedContainAsync(string nameField, string st) {
            return base.Channel.GetListClientsBySelectedContainAsync(nameField, st);
        }
        
        public SAFRANIT.SHARAT.Publish[] GetListPublishBySelectedContain(string nameField, string st) {
            return base.Channel.GetListPublishBySelectedContain(nameField, st);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.Publish[]> GetListPublishBySelectedContainAsync(string nameField, string st) {
            return base.Channel.GetListPublishBySelectedContainAsync(nameField, st);
        }
        
        public SAFRANIT.SHARAT.BooksList[] GetListBooksListBySelectedContain(string nameField, string st) {
            return base.Channel.GetListBooksListBySelectedContain(nameField, st);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.BooksList[]> GetListBooksListBySelectedContainAsync(string nameField, string st) {
            return base.Channel.GetListBooksListBySelectedContainAsync(nameField, st);
        }
        
        public SAFRANIT.SHARAT.BookToBorrow[] GetListBookToBorrowBySelectedContain(string nameField, string st) {
            return base.Channel.GetListBookToBorrowBySelectedContain(nameField, st);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.BookToBorrow[]> GetListBookToBorrowBySelectedContainAsync(string nameField, string st) {
            return base.Channel.GetListBookToBorrowBySelectedContainAsync(nameField, st);
        }
        
        public SAFRANIT.SHARAT.BorrowingExplaning[] GetListBorrowingExplaningBySelectedContain(string nameField, string st) {
            return base.Channel.GetListBorrowingExplaningBySelectedContain(nameField, st);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.BorrowingExplaning[]> GetListBorrowingExplaningBySelectedContainAsync(string nameField, string st) {
            return base.Channel.GetListBorrowingExplaningBySelectedContainAsync(nameField, st);
        }
        
        public SAFRANIT.SHARAT.SignUp[] GetListSignUpBySelectedContain(string nameField, string st) {
            return base.Channel.GetListSignUpBySelectedContain(nameField, st);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.SignUp[]> GetListSignUpBySelectedContainAsync(string nameField, string st) {
            return base.Channel.GetListSignUpBySelectedContainAsync(nameField, st);
        }
        
        public SAFRANIT.SHARAT.Borrowing[] GetListBorrowingBySelectedContain(string nameField, string st) {
            return base.Channel.GetListBorrowingBySelectedContain(nameField, st);
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.Borrowing[]> GetListBorrowingBySelectedContainAsync(string nameField, string st) {
            return base.Channel.GetListBorrowingBySelectedContainAsync(nameField, st);
        }
        
        public SAFRANIT.SHARAT.KindsOfBook[] GetListKindsOfBook() {
            return base.Channel.GetListKindsOfBook();
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.KindsOfBook[]> GetListKindsOfBookAsync() {
            return base.Channel.GetListKindsOfBookAsync();
        }
        
        public SAFRANIT.SHARAT.TypesFORbook[] GetListTypesFORbook() {
            return base.Channel.GetListTypesFORbook();
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.TypesFORbook[]> GetListTypesFORbookAsync() {
            return base.Channel.GetListTypesFORbookAsync();
        }
        
        public SAFRANIT.SHARAT.Clients[] GetListClients() {
            return base.Channel.GetListClients();
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.Clients[]> GetListClientsAsync() {
            return base.Channel.GetListClientsAsync();
        }
        
        public SAFRANIT.SHARAT.Publish[] GetListPublish() {
            return base.Channel.GetListPublish();
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.Publish[]> GetListPublishAsync() {
            return base.Channel.GetListPublishAsync();
        }
        
        public SAFRANIT.SHARAT.BooksList[] GetListBooksList() {
            return base.Channel.GetListBooksList();
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.BooksList[]> GetListBooksListAsync() {
            return base.Channel.GetListBooksListAsync();
        }
        
        public SAFRANIT.SHARAT.BookToBorrow[] GetListBookToBorrow() {
            return base.Channel.GetListBookToBorrow();
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.BookToBorrow[]> GetListBookToBorrowAsync() {
            return base.Channel.GetListBookToBorrowAsync();
        }
        
        public SAFRANIT.SHARAT.BorrowingExplaning[] GetListBorrowingExplaning() {
            return base.Channel.GetListBorrowingExplaning();
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.BorrowingExplaning[]> GetListBorrowingExplaningAsync() {
            return base.Channel.GetListBorrowingExplaningAsync();
        }
        
        public SAFRANIT.SHARAT.SignUp[] GetListSignUp() {
            return base.Channel.GetListSignUp();
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.SignUp[]> GetListSignUpAsync() {
            return base.Channel.GetListSignUpAsync();
        }
        
        public SAFRANIT.SHARAT.Borrowing[] GetListBorrowing() {
            return base.Channel.GetListBorrowing();
        }
        
        public System.Threading.Tasks.Task<SAFRANIT.SHARAT.Borrowing[]> GetListBorrowingAsync() {
            return base.Channel.GetListBorrowingAsync();
        }
        
        public int GetNextKeyKindsOfBook() {
            return base.Channel.GetNextKeyKindsOfBook();
        }
        
        public System.Threading.Tasks.Task<int> GetNextKeyKindsOfBookAsync() {
            return base.Channel.GetNextKeyKindsOfBookAsync();
        }
        
        public int GetNextKeyPublish() {
            return base.Channel.GetNextKeyPublish();
        }
        
        public System.Threading.Tasks.Task<int> GetNextKeyPublishAsync() {
            return base.Channel.GetNextKeyPublishAsync();
        }
        
        public int GetNextKeyBooksList() {
            return base.Channel.GetNextKeyBooksList();
        }
        
        public System.Threading.Tasks.Task<int> GetNextKeyBooksListAsync() {
            return base.Channel.GetNextKeyBooksListAsync();
        }
        
        public int GetNextKeyBorrowing() {
            return base.Channel.GetNextKeyBorrowing();
        }
        
        public System.Threading.Tasks.Task<int> GetNextKeyBorrowingAsync() {
            return base.Channel.GetNextKeyBorrowingAsync();
        }
        
        public int GetNextKeyBookToBorrow() {
            return base.Channel.GetNextKeyBookToBorrow();
        }
        
        public System.Threading.Tasks.Task<int> GetNextKeyBookToBorrowAsync() {
            return base.Channel.GetNextKeyBookToBorrowAsync();
        }
        
        public string GetCurrentPath() {
            return base.Channel.GetCurrentPath();
        }
        
        public System.Threading.Tasks.Task<string> GetCurrentPathAsync() {
            return base.Channel.GetCurrentPathAsync();
        }
        
        public void SaveImg(byte[] imageArr, string nameFile) {
            base.Channel.SaveImg(imageArr, nameFile);
        }
        
        public System.Threading.Tasks.Task SaveImgAsync(byte[] imageArr, string nameFile) {
            return base.Channel.SaveImgAsync(imageArr, nameFile);
        }
        
        public byte[] GetImage(string fileName) {
            return base.Channel.GetImage(fileName);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetImageAsync(string fileName) {
            return base.Channel.GetImageAsync(fileName);
        }
    }
}
